#!/usr/bin/env python3
"""
Python port of mu2ejobfcl Perl script.
Generates FCL configuration files for Mu2e jobs.
"""

import argparse
import os
import sys
from typing import Dict, List, Optional, Union
import re

# Allow running this file directly: make package root importable
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.job_common import Mu2eName, Mu2eJobBase
from utils.file_resolver import FileResolver


_OUTPUT_FILENAME_KEY_RE = re.compile(r'^outputs\.\w+\.fileName$')
_PLACEHOLDER_TOKEN_RE = re.compile(r'\b(description|desc|owner|version|sequencer)\b')


def _check_output_filenames_substituted(outputs_dict: Dict[str, str], jobdef_name: str = "") -> None:
    """Reject output fileNames that still contain unsubstituted placeholder
    tokens. Fires when an upstream fcl declares an output with a suffix
    glued to the desc token (e.g. description-CH) and the entry's
    fcl_overrides didn't add an explicit {desc}-CH override. See memory
    reference_reco_output_suffix_overrides."""
    for key, filename in outputs_dict.items():
        if not _OUTPUT_FILENAME_KEY_RE.match(key):
            continue
        m = _PLACEHOLDER_TOKEN_RE.search(filename)
        if m:
            raise ValueError(
                f"jobfcl: {key} = {filename!r} contains unsubstituted placeholder "
                f"{m.group(1)!r} (jobdef={jobdef_name}). Add an explicit override "
                f"in the entry's fcl_overrides (e.g. \"mcs.owner.{{desc}}-CH.version.sequencer.art\")."
            )


def validate_output_filenames(jobdef_path: str, index: int = 0) -> None:
    """Cheaply validate a cnf tarball's output filenames substitute cleanly.
    Raises ValueError if any outputs.*.fileName has a literal placeholder
    (description / owner / version / sequencer) surviving substitution."""
    job_fcl = Mu2eJobFCL(jobdef_path)
    _check_output_filenames_substituted(job_fcl.job_outputs(index), jobdef_name=jobdef_path)


class Mu2eJobFCL(Mu2eJobBase):
    """Python port of mu2ejobfcl functionality."""

    def __init__(self, jobdef: str, inloc: str = 'tape', proto: str = 'file'):
        """Initialize with job definition file."""
        super().__init__(jobdef)
        self.inloc = inloc
        self.proto = proto
        self._resolver = FileResolver(inloc=inloc, proto=proto)

        # Cache the source type detection
        self._source_type = None
    
    def _get_source_type(self) -> str:
        """Detect the source module type from the base FCL."""
        if self._source_type is None:
            base_fcl = self._extract_fcl()
            # Look for module_type in source configuration
            if 'module_type : SamplingInput' in base_fcl or 'module_type: SamplingInput' in base_fcl:
                self._source_type = 'SamplingInput'
            elif 'module_type : RootInput' in base_fcl or 'module_type: RootInput' in base_fcl:
                self._source_type = 'RootInput'
            elif 'module_type : EmptyEvent' in base_fcl or 'module_type: EmptyEvent' in base_fcl:
                self._source_type = 'EmptyEvent'
            else:
                # Unknown source type - treat as None
                self._source_type = 'Unknown'
        return self._source_type
    
    def _extract_fcl(self) -> str:
        """Extract mu2e.fcl from the tarball."""
        return self._extract_member('mu2e.fcl').decode('utf-8')
    

    
    def _locate_file(self, filename: str) -> str:
        """Locate a file and return its physical path (see FileResolver)."""
        return self._resolver.locate(filename)

    def _format_filename(self, filename: str) -> str:
        """Format filename according to protocol (see FileResolver)."""
        return self._resolver.url(filename)

    def index_from_sequencer(self, seq: str) -> int:
        """Get job index from sequencer."""
        nj = self.njobs()
        if nj > 0:
            # Finite job set - search exhaustively
            for i in range(nj):
                if self.sequencer(i) == seq:
                    return i
            raise ValueError(f"Outputs with the requested sequencer \"{seq}\" are not produced by this jobset.")
        else:
            # Infinite job set - parse sequencer
            # Format: run_subrun
            parts = seq.split('_')
            if len(parts) != 2:
                raise ValueError(f"Unexpected format of the sequencer \"{seq}\"")
            
            index = int(parts[1])
            # Verify
            test_seq = self.sequencer(index)
            if test_seq != seq:
                raise ValueError(f"Outputs with the requested sequencer \"{seq}\" are not generated by this jobset.")
            return index
    
    def index_from_source_file(self, srcfn: str) -> int:
        """Get job index from source file."""
        tbs = self.json_data.get('tbs', {})
        inputs = tbs.get('inputs')
        
        if inputs:
            for dataset, (merge, filelist) in inputs.items():
                try:
                    fileindex = filelist.index(srcfn)
                    return fileindex // merge
                except ValueError:
                    continue
        
        raise ValueError(f"This jobset does not use \"{srcfn}\" as a primary input file")
    
    def find_index(self, index: Optional[int] = None, target: Optional[str] = None, source: Optional[str] = None) -> int:
        """Find job index from various input methods."""
        if index is not None:
            if target is not None:
                raise ValueError("Error: --index and --target are mutually exclusive")
            if source is not None:
                raise ValueError("Error: --index and --source are mutually exclusive")
            return index
        
        if target is not None:
            if source is not None:
                raise ValueError("Error: --target and --source are mutually exclusive")
            
            seq = Mu2eName.parse(target).sequencer
            job_index = self.index_from_sequencer(seq)
            
            # Check that the target file matches what this job will produce
            outputs = self.job_outputs(job_index)
            for output_file in outputs.values():
                if output_file == target:
                    return job_index
            
            raise ValueError(f"Error: file \"{target}\" is not produced by any job in this job set.")
        
        if source is not None:
            return self.index_from_source_file(source)
        
        raise ValueError("Error: one of --index, --target, or --source must be specified.")
    
    def generate_fcl(self, index: int) -> str:
        """Generate FCL configuration for job index."""
        # Get base FCL
        base_fcl = self._extract_fcl()
        
        # Generate additional configuration
        config_lines = []
        config_lines.append("#----------------------------------------------------------------")
        config_lines.append(f"# Code added by mu2ejobfcl for job index {index}:")
        
        # Event settings
        event_settings = self.job_event_settings(index)
        for key, value in event_settings.items():
            config_lines.append(f"{key}: {value}")
        
        # SamplingInput-specific settings: different sampling seed for each job
        source_type = self._get_source_type()
        if source_type == 'SamplingInput':
            config_lines.append(f"source.samplingSeed: {1 + index}")
        
        # Input files with protocol handling. Batch-locate everything in
        # one SAM round-trip first — per-file lookups cost ~90 sequential
        # HTTP calls for a mixing job (primaries + pileup).
        inputs = self.job_inputs(index)
        self._resolver.prefetch(
            [f for file_list in inputs.values() for f in file_list])
        for key, file_list in inputs.items():
            if file_list:
                config_lines.append(f"{key}: [")
                for i, filename in enumerate(file_list):
                    formatted_filename = self._format_filename(filename)
                    comma = "," if i < len(file_list) - 1 else ""
                    config_lines.append(f'    "{formatted_filename}"{comma}')
                config_lines.append("]")
        
        # Output files (add/replace outputs from job definition)
        outputs = self.job_outputs(index)
        _check_output_filenames_substituted(outputs, jobdef_name=self.jobdef)
        for key, filename in outputs.items():
            # Always add the output from job definition (it may replace template values)
            config_lines.append(f'{key}: "{filename}"')
        
        # Seed settings
        seed_settings = self.job_seed(index)
        for key, value in seed_settings.items():
            config_lines.append(f"{key}: {value}")
        
        config_lines.append("# End code added by mu2ejobfcl:")
        config_lines.append("#----------------------------------------------------------------")
        
        # Combine base FCL with additional configuration
        return base_fcl + "\n" + "\n".join(config_lines)

def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description='Python port of mu2ejobfcl - generates FCL configuration files for Mu2e jobs'
    )
    parser.add_argument('--jobdef', required=True, help='Job definition file (cnf.tar)')
    parser.add_argument('--index', type=int, help='Job index')
    parser.add_argument('--target', help='Target output file name')
    parser.add_argument('--source', help='Source input file name')
    parser.add_argument('--default-location', '--default-loc', default='tape',
                       help='Default location for input files (default: tape). Use "stash" to prefer stash with automatic fallback to tape. Use "resilient" for resilient dCache (xrootd).')
    parser.add_argument('--default-protocol', '--default-proto', default='file',
                       help='Default protocol for input files (default: file)')
    
    args = parser.parse_args()
    
    # Validate file exists and is readable
    if not os.path.isfile(args.jobdef):
        print(f"Error: {args.jobdef} is not a file", file=sys.stderr)
        sys.exit(1)
    
    if not os.access(args.jobdef, os.R_OK):
        print(f"Error: file {args.jobdef} is not readable", file=sys.stderr)
        sys.exit(1)
    
    try:
        job_fcl = Mu2eJobFCL(args.jobdef, inloc=getattr(args, 'default_location'), proto=getattr(args, 'default_protocol'))
        
        # Find job index
        index = job_fcl.find_index(args.index, args.target, args.source)
        
        # Validate index
        if index < 0:
            print(f"Error: --index must be non-negative, got: {index}", file=sys.stderr)
            sys.exit(1)
        
        # Check if index is in range
        njobs = job_fcl.njobs()
        if njobs > 0 and index >= njobs:
            print(f"Zero based index {index} is too large for njobs = {njobs}", file=sys.stderr)
            sys.exit(1)
        
        # Generate and print FCL
        fcl_content = job_fcl.generate_fcl(index)
        print(fcl_content)
    
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
